language: cpp
compiler:
  - gcc
before_script:
  - echo yes | sudo add-apt-repository ppa:marco89-7/root
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev-i386 root-system libmysql++-dev libsqlite3-dev
  - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-test-dev
  - mkdir build
  - cd build
  - cmake .. -DFORCE_32BIT=OFF
script:
  - make
  - ./asym -h # dummy run all executables
  - ./malpha -h # for example checks for dynamic libraries loading
  - ./masym -h
#  - ./spinflipper
